---
- name: Install Docker
  apt:
    name:
    - docker.io
    state: present


- name: Add the concourse group
  become: true
  ansible.builtin.group:
    name: concourse
    state: present
    system: true

- name: Add the concourse user
  become: true
  ansible.builtin.user:
    name: concourse
    password: "{{ concoursePassword }}"
    update_password: always
    comment: Concourse User
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    groups: 
      - root
      - concourse
      - docker
    state: present


- name: Create concourse etc directory
  become: true
  ansible.builtin.file:
    path: /etc/concourse
    state: directory
    # owner: concourse
    # group: concourse
    owner: root
    group: root
    mode: '0777'

- name: Create concourse /var/lib directory
  become: true
  ansible.builtin.file:
    path: /var/lib/concourse
    state: directory
    owner: concourse
    group: concourse
    mode: '0755'

- name: Fetch the keys from master
  copy:
    dest: /etc/concourse/
    src: "buffer/{{ item }}" 
    owner: concourse
    group: concourse
    mode: '0644'
  with_items:
    - tsa_host_key.pub
    - worker_key

- name: Create /etc/concourse/worker_environment configuration file
  become: true
  # no_log: true
  ansible.builtin.lineinfile:
    path: /etc/concourse/worker_environment
    regexp: "{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    state: present
    create: true
    owner: concourse
    group: concourse
    mode: 600
  with_items:
    - key: CONCOURSE_WORK_DIR
      value: /var/lib/concourse
    - key: CONCOURSE_TSA_HOST
      value: "{{ concourseFQDN }}:2222"
    - key: CONCOURSE_TSA_PUBLIC_KEY
      value: /etc/concourse/tsa_host_key.pub
    - key: CONCOURSE_TSA_WORKER_PRIVATE_KEY
      value: /etc/concourse/worker_key
    - key: CONCOURSE_RUNTIME
      value: containerd
    - key: CONCOURSE_CONTAINERD_DNS_SERVER
      value: 192.168.2.1

- name: Copy systemd init file
  template:
    src: files/concourse-worker.service
    dest: /etc/systemd/system/concourse-worker.service
    owner: root
    group: root
    mode: 0777
  # notify: systemd_reload

- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start The Services
  service:
    name: "{{ item }}"
    state: started
    daemon_reload: yes
    enabled: yes
  with_items: 
    - concourse-worker
    - docker
